apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: horovod-volcano-sothisai
spec:
  minAvailable: 1
  schedulerName: volcano
  # 作业插件机制
  plugins:
    # env插件，提供任务索引。如下面Commond中的VK_TASK_INDEX
    env: []
    # SVC插件，支持作业内pod间互访，并提供访问地址。
    svc: []
    ssh: []
  # 异常场景处理：当有任意一个Pod被驱逐时，它处理的方式都是重启整个Job
  policies:
    - event: PodEvicted
      action: RestartJob
  queue: default
  # 作业的task角色
  tasks:
    - replicas: 1
      name: w0
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        metadata:
          labels:
            containerIndex: "0"
            containerType: worker
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - /bin/cat /proc/1/environ| /usr/bin/tr '\0' '\n' | grep -v HOME | /usr/bin/awk
                  -v ex='export ' '{printf ex;print $1}'> /etc/profile.d/sothisai.sh 
                  && /usr/sbin/sshd
                  && su - alex -c " touch /home/alex/SothisAI/tensorflow/tf_task/TF_Horovod-02/horovod-volcano-sothisai.worker_0.log"  
                  && sh /home/alex/SothisAI/tensorflow/tf_task/TF_Horovod-single_01/exec.sh /home/alex/SothisAI/tensorflow/tf_task/TF_Horovod-single_01/.running 0
                  && su - alex -c "cd /home/alex/sothisai_2.8.0_example_scripts/tensorflow_test/tf_train/
                  && horovodrun -np 1 -H $VC_W0_HOSTS:1
                  python '/home/alex/sothisai_2.8.0_example_scripts/tensorflow_test/tf_train/mnist_horovod.py'
                  > /home/alex/SothisAI/tensorflow/tf_task/TF_Horovod-02/horovod-volcano-sothisai.worker_0.log
                  2>&1"; rm -rf /home/alex/SothisAI/tensorflow/tf_task/TF_Horovod-single_01/.running
              image: image.ac.com:5000/gpu/admin/tfhorovod/tensorflow:1.15-cuda11.8-py3.8-gloo
              name: w0
              # ports,声明ssh通信时访问的端口号
              ports:
                - containerPort: 2222
                  name: w0-port
              resources:
                limits:
                  cpu: "1"
                  memory: 8Gi
                  nvidia.com/gpu: "1"
                requests:
                  cpu: "1"
                  memory: 8Gi
                  nvidia.com/gpu: "1"
              volumeMounts:
                - mountPath: /home/alex
                  name: scriptpath
                - mountPath: /etc/localtime
                  name: localtime
                  readOnly: true
                - mountPath: /etc/sudoers.d/ai_sudo
                  name: sudoerv
                - mountPath: /etc/passwd
                  name: passwdv
                - mountPath: /etc/group
                  name: groupv
                - mountPath: /etc/shadow
                  name: shadowv
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /etc/tmp
                  name: tmpv
                - mountPath: /usr/bin/kubectl
                  name: kubecntr
          nodeSelector:
            resourceGroup: normal
          restartPolicy: Never
          volumes:
            - hostPath:
                path: /home/alex
                type: ""
              name: scriptpath
            - hostPath:
                path: /etc/localtime
                type: ""
              name: localtime
            - hostPath:
                path: /home/alex/.ai_user_info/ai_sudoer
                type: ""
              name: sudoerv
            - hostPath:
                path: /home/alex/.ai_user_info/ai_passwd
                type: ""
              name: passwdv
            - hostPath:
                path: /home/alex/.ai_user_info/ai_group
                type: ""
              name: groupv
            - hostPath:
                path: /home/alex/.ai_user_info/ai_shadow
                type: ""
              name: shadowv
            - emptyDir:
                medium: Memory
              name: dshm
            - hostPath:
                path: /etc/tmp
                type: ""
              name: tmpv
            - hostPath:
                path: /usr/bin/kubectl
                type: ""
              name: kubecntr
