apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nginx-vol"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data/kubernetes/pv/nginx-vol
