apiVersion: batch/v1
kind: Job
metadata:
  labels:
    containerIndex: "0"
    containerType: ps
    svcname: tf-task-2303137912-alex-87738-p0
    taskId: tf-task-2303137912-alex-87738
  name: tf-task-2303137912-alex-87738-p0
  namespace: alex
spec:
  activeDeadlineSeconds: 36000
  backoffLimit: 0
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 1d5a10eb-2f1d-4800-937d-aa9bbfe4291d
  template:
    metadata:
      creationTimestamp: null
      labels:
        containerIndex: "0"
        containerType: ps
        controller-uid: 1d5a10eb-2f1d-4800-937d-aa9bbfe4291d
        job-name: tf-task-2303137912-alex-87738-p0
        svcname: tf-task-2303137912-alex-87738-p0
        taskId: tf-task-2303137912-alex-87738
      name: tf-task-2303137912-alex-87738-p0
      namespace: alex
    spec:
      activeDeadlineSeconds: 36000
      containers:
      - command:
        - /bin/sh
        - -c
        - /bin/cat /proc/1/environ| /usr/bin/tr '\0' '\n' | grep -v HOME | /usr/bin/awk
          -v ex='export ' '{printf ex;print $1}'> /etc/profile.d/sothisai.sh &&/usr/sbin/sshd
          && su - alex -c " cd /home/alex/sothisai_2.8.0_example_scripts/tensorflow_test/tf_train/
          && CUDA_VISIBLE_DEVICES='' python '/home/alex/sothisai_2.8.0_example_scripts/tensorflow_test/tf_train/mnist_dist.py'
          --ps_hosts=$TF_TASK_2303137912_ALEX_87738_P0_SERVICE_HOST:2222 --worker_hosts=$TF_TASK_2303137912_ALEX_87738_W0_SERVICE_HOST:2222
          --job_name=ps --task_index=0 > /home/alex/SothisAI/tensorflow/tf_task/TF_Task_2303137912/tf-task-2303137912-alex-87738.ps_0.log
          2>&1"
        image: image.ac.com:5000/gpu/admin/tensorflow/tensorflow:1.13-py2.7-CUDA10.0
        imagePullPolicy: IfNotPresent
        name: tf-task-2303137912-alex-87738-p0
        ports:
        - containerPort: 2222
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
            nvidia.com/gpu: "0"
          requests:
            cpu: "2"
            memory: 4Gi
            nvidia.com/gpu: "0"
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/alex
          name: scriptpath
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /etc/sudoers.d/ai_sudo
          name: sudoerv
        - mountPath: /etc/passwd
          name: passwdv
        - mountPath: /etc/group
          name: groupv
        - mountPath: /etc/shadow
          name: shadowv
        - mountPath: /dev/shm
          name: dshm
      dnsPolicy: Default
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      volumes:
      - hostPath:
          path: /home/alex
          type: ""
        name: scriptpath
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - hostPath:
          path: /home/alex/.ai_user_info/ai_sudoer
          type: ""
        name: sudoerv
      - hostPath:
          path: /home/alex/.ai_user_info/ai_passwd
          type: ""
        name: passwdv
      - hostPath:
          path: /home/alex/.ai_user_info/ai_group
          type: ""
        name: groupv
      - hostPath:
          path: /home/alex/.ai_user_info/ai_shadow
          type: ""
        name: shadowv
      - emptyDir:
          medium: Memory
        name: dshm
