apiVersion: v1
kind: Pod
metadata:
  name: nginx-emptydir-memory
spec:
  containers:
    - image: Nginx
      name: tensorflow-emptydir-memory
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir:
        medium: Memory