apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: tensorflow-dist-mnist
spec:
  minAvailable: 3
  schedulerName: volcano
  # 作业插件机制
  plugins:
    # env插件，提供任务索引。如下面Commond中的VK_TASK_INDEX
    env: []
    # SVC插件，支持作业内pod间互访，并提供访问地址。如下面Commond中的ps.host和worker.host
    svc: []
  # 异常场景处理：当有任意一个Pod被驱逐时，它处理的方式都是重启整个Job  
  policies:
    - event: PodEvicted
      action: RestartJob
  queue: default
  # 作业的task角色
  tasks:
    - replicas: 1
      name: ps
      template:
        spec:
          containers:
            # HOST声明ps和worker任务通信时采用的host,由svc插件创建
            - command:
                - sh
                - -c
                - |
                  PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"ps\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
                  python /var/tf_dist_mnist/dist_mnist.py
              image: volcanosh/dist-mnist-tf-example:0.0.1
              name: tensorflow
              # ports,声明ssh通信时访问的端口号
              ports:
                - containerPort: 2222
                  name: tfjob-port
              resources: {}
          restartPolicy: Never
    - replicas: 2
      name: worker
      # 当所有的Worker正常结束变成Completed状态，意味着整个Job正常结束
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            # HOST声明ps和worker任务通信时采用的host,由svc插件创建
            - command:
                - sh
                - -c
                - |
                  PS_HOST=`cat /etc/volcano/ps.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  WORKER_HOST=`cat /etc/volcano/worker.host | sed 's/$/&:2222/g' | sed 's/^/"/;s/$/"/' | tr "\n" ","`;
                  export TF_CONFIG={\"cluster\":{\"ps\":[${PS_HOST}],\"worker\":[${WORKER_HOST}]},\"task\":{\"type\":\"worker\",\"index\":${VK_TASK_INDEX}},\"environment\":\"cloud\"};
                  python /var/tf_dist_mnist/dist_mnist.py
              image: volcanosh/dist-mnist-tf-example:0.0.1
              name: tensorflow
              # ports,声明ssh通信时访问的端口号
              ports:
                - containerPort: 2222
                  name: tfjob-port
              resources: {}
          restartPolicy: Never