apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox:1.28.3
    imagePullPolicy: IfNotPresent
    name: busybox
    command:
    - "sleep"
    - "3600"
    resources: {}
    envFrom:
    - configMapRef:
        name: busybox-users
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
