apiVersion: v1
kind: Pod
metadata:
  name: configmap-redis
  labels:
    volume: configmap
  annotations:
    kubernetes.io/storage: emptyDir
spec:
  containers:
    - name: configmap-redis
      image: redis:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: redis-6379-port
          protocol: TCP
          containerPort: 6379
      #将定义的驱动emptydir-redis挂载到容器的/data目录，通过名字方式关联
      volumeMounts:
        - name: configmap-redis
          mountPath: /data
  #定义一个存储，驱动类型为emptyDir，大小1G
  volumes:
    - name: configmap-redis
      emptyDir:
        sizeLimit: 1Gi