apiVersion: v1
kind: Pod
metadata:
  name: cpu-mem-request-limit
  namespace: 1-kubernetes
  labels:
    name: cpu-mem-request-limit
spec:
  containers:
    - name: cpu-mem-request-limit
      image: nginx:1.7.9
      imagePullPolicy: IfNotPresent
      ports:
        - name: nginx-port-80
          protocol: TCP
          containerPort: 80
      resources:
        requests:
          cpu: 0.25
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi