# 通过设置 -cpu "2"，你将容器配置为尝试使用 2 个 CPU，
# 但是容器只被允许使用大约 1 个 CPU。
# 容器的 CPU 用量受到限制，因为该容器正尝试使用超出其限制的 CPU 资源。
apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: 1-kubernetes
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
    args:
    - -cpus
    - "2"
