apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
  namespace: 1-kubernetes
spec:
  containers:
  - name: memory-demo-2-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"
    command: ["stress"]
    # 超过容器限制的内存会OOM
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
