apiVersion: batch/v1
kind: Job
metadata:
  labels:
    containerIndex: "0"
    containerType: worker
    svcname: pytorch-horovod-01-alex-91104-w0
    taskId: pytorch-horovod-01-alex-91104
  name: pytorch-horovod-01-alex-91104-w0
  namespace: alex
spec:
  activeDeadlineSeconds: 36000
  backoffLimit: 0
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 4cf68f6d-5e09-40af-8835-b7979bb213e2
  template:
    metadata:
      creationTimestamp: null
      labels:
        containerIndex: "0"
        containerType: worker
        controller-uid: 4cf68f6d-5e09-40af-8835-b7979bb213e2
        job-name: pytorch-horovod-01-alex-91104-w0
        svcname: pytorch-horovod-01-alex-91104-w0
        taskId: pytorch-horovod-01-alex-91104
      name: pytorch-horovod-01-alex-91104-w0
      namespace: alex
    spec:
      activeDeadlineSeconds: 36000
      containers:
      - command:
        - /bin/sh
        - -c
        - /bin/cat /proc/1/environ| /usr/bin/tr '\0' '\n' | grep -v HOME | /usr/bin/awk
          -v ex='export ' '{printf ex;print $1}'> /etc/profile.d/sothisai.sh && /usr/sbin/sshd
          && su - alex -c " touch /home/alex/SothisAI/pytorch/pytorch_task/Pytorch_Horovod_01/pytorch-horovod-01-alex-91104.worker_0.log"  &&
          sh /home/alex/SothisAI/pytorch/pytorch_task/Pytorch_Horovod_01/exec.sh /home/alex/SothisAI/pytorch/pytorch_task/Pytorch_Horovod_01/.running
          1&&su - alex -c "cd /home/alex/sothisai_2.8.0_example_scripts/pytorch_test/pytorch_train/
          && mpirun -np 2 -H $PYTORCH_HOROVOD_01_ALEX_91104_W0_SERVICE_HOST:1,$PYTORCH_HOROVOD_01_ALEX_91104_W1_SERVICE_HOST:1
          -bind-to none -map-by slot  -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca
          btl ^openib python '/home/alex/sothisai_2.8.0_example_scripts/pytorch_test/pytorch_train/mnist_horovod.py'
          > /home/alex/SothisAI/pytorch/pytorch_task/Pytorch_Horovod_01/pytorch-horovod-01-alex-91104.worker_0.log
          2>&1"; rm -rf /home/alex/SothisAI/pytorch/pytorch_task/Pytorch_Horovod_01/.running
        image: image.ac.com:5000/gpu/admin/pytorchhorovod/pytorch:1.2-py3.6-CUDA10.0
        imagePullPolicy: IfNotPresent
        name: pytorch-horovod-01-alex-91104-w0
        ports:
        - containerPort: 2222
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 8Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "1"
            memory: 8Gi
            nvidia.com/gpu: "1"
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/alex
          name: scriptpath
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /etc/sudoers.d/ai_sudo
          name: sudoerv
        - mountPath: /etc/passwd
          name: passwdv
        - mountPath: /etc/group
          name: groupv
        - mountPath: /etc/shadow
          name: shadowv
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /etc/tmp
          name: tmpv
        - mountPath: /etc/ssh/sshd_config
          name: sshconfig
        - mountPath: /usr/bin/kubectl
          name: kubecntr
      dnsPolicy: Default
      nodeSelector:
        resourceGroup: normal
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      volumes:
      - hostPath:
          path: /home/alex
          type: ""
        name: scriptpath
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - hostPath:
          path: /home/alex/.ai_user_info/ai_sudoer
          type: ""
        name: sudoerv
      - hostPath:
          path: /home/alex/.ai_user_info/ai_passwd
          type: ""
        name: passwdv
      - hostPath:
          path: /home/alex/.ai_user_info/ai_group
          type: ""
        name: groupv
      - hostPath:
          path: /home/alex/.ai_user_info/ai_shadow
          type: ""
        name: shadowv
      - emptyDir:
          medium: Memory
        name: dshm
      - hostPath:
          path: /etc/tmp
          type: ""
        name: tmpv
      - hostPath:
          path: /etc/ssh/sshd_config
          type: ""
        name: sshconfig
      - hostPath:
          path: /usr/bin/kubectl
          type: ""
        name: kubecntr
