apiVersion: batch/v1
kind: Job
metadata:
  labels:
    containerIndex: "0"
    containerType: worker
    svcname: pytorch-task-2303243623-alex-61514-w0
    taskId: pytorch-task-2303243623-alex-61514
  name: pytorch-task-2303243623-alex-61514-w0
  namespace: alex
spec:
  activeDeadlineSeconds: 36000
  backoffLimit: 0
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 670a7efc-71b3-4ca9-aab7-9b6589ec7f77
  template:
    metadata:
      creationTimestamp: null
      labels:
        containerIndex: "0"
        containerType: worker
        controller-uid: 670a7efc-71b3-4ca9-aab7-9b6589ec7f77
        job-name: pytorch-task-2303243623-alex-61514-w0
        svcname: pytorch-task-2303243623-alex-61514-w0
        taskId: pytorch-task-2303243623-alex-61514
      name: pytorch-task-2303243623-alex-61514-w0
      namespace: alex
    spec:
      activeDeadlineSeconds: 36000
      containers:
      - command:
        - /bin/sh
        - -c
        - /bin/cat /proc/1/environ| /usr/bin/tr '\0' '\n' | grep -v HOME | /usr/bin/awk
          -v ex='export ' '{printf ex;print $1}'> /etc/profile.d/sothisai.sh &&/usr/sbin/sshd
          && su - alex -c " cd /home/alex/sothisai_2.8.0_example_scripts/pytorch_test/pytorch_train/
          && python '/home/alex/sothisai_2.8.0_example_scripts/pytorch_test/pytorch_train/mnist_distributed.py'
          --rank 0 --world-size 2 --ip 127.0.0.1 --port 2222 >> /home/alex/SothisAI/pytorch/pytorch_task/Pytorch_Task_2303243623/pytorch-task-2303243623-alex-61514.worker_0.log
          2>&1"
        image: image.ac.com:5000/gpu/admin/pytorch/pytorch:1.0-py3.6-CUDA10.0
        imagePullPolicy: IfNotPresent
        name: pytorch-task-2303243623-alex-61514-w0
        ports:
        - containerPort: 2222
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 8Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: "1"
            memory: 8Gi
            nvidia.com/gpu: "1"
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/alex
          name: scriptpath
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /etc/sudoers.d/ai_sudo
          name: sudoerv
        - mountPath: /etc/passwd
          name: passwdv
        - mountPath: /etc/group
          name: groupv
        - mountPath: /etc/shadow
          name: shadowv
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /etc/tmp
          name: tmpv
        - mountPath: /etc/ssh/sshd_config
          name: sshconfig
        - mountPath: /usr/bin/kubectl
          name: kubecntr
      dnsPolicy: Default
      nodeSelector:
        resourceGroup: normal
      restartPolicy: Never
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
      volumes:
      - hostPath:
          path: /home/alex
          type: ""
        name: scriptpath
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - hostPath:
          path: /home/alex/.ai_user_info/ai_sudoer
          type: ""
        name: sudoerv
      - hostPath:
          path: /home/alex/.ai_user_info/ai_passwd
          type: ""
        name: passwdv
      - hostPath:
          path: /home/alex/.ai_user_info/ai_group
          type: ""
        name: groupv
      - hostPath:
          path: /home/alex/.ai_user_info/ai_shadow
          type: ""
        name: shadowv
      - emptyDir:
          medium: Memory
        name: dshm
      - hostPath:
          path: /etc/tmp
          type: ""
        name: tmpv
      - hostPath:
          path: /etc/ssh/sshd_config
          type: ""
        name: sshconfig
      - hostPath:
          path: /usr/bin/kubectl
          type: ""
        name: kubecntr
